NGLogmanServer/urls.py
from django.contrib import admin
from django.urls import path, include
import sys
import threading
from nglm_grpc.gRPCMethods import checkNodes

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('nglogman.urls'))
]


# call config and logging module here

# TODO: Expand on 'Failed' Task display (separate page, which failed, log)
# TODO: Clientside Failure Criteria
# TODO: Use pickle real time data streaming to alleviate RAM usage

# add gRPC server start point here
if sys.version_info[0] < 3:
    raise Exception("Must be using Python 3.")

if 'runserver' in sys.argv:
    import grpc

    from nglm_grpc.modules.Utility import singletonThreadPool
    from nglm_grpc.gRPCMethods import addToServer, checkNodes
    from nglogman.models import LGNode

    server = grpc.server(singletonThreadPool(max_workers=10))
    addToServer(server)
    server.add_insecure_port('[::]:50051')
    server.start()

    threading.Thread(
        target=checkNodes, kwargs={'repeat': True}
    ).start()

nglogman/urls.py
from django.urls import include, path, re_path
from . import views
from . import api_views
from django.http import HttpResponseRedirect
from rest_framework import routers
from NGLogmanServer.settings import OUTPUT_ROOT, STATICFILES_DIRS

urlpatterns = [
    path('', lambda r: HttpResponseRedirect('dashboard')),
    path('dashboard', views.DashboardView, name='dashboard'),
    path('tasks', views.TaskListView, name='tasks'),
    path('groups', views.GroupListView, name='groups'),
    re_path(r'^groups/(?P<groupID>\d+)/config$', views.ConfigUpload),
    path('nodes', views.NodeListView, name='nodes'),
    re_path(r'^nodeConfigs/(?P<path>.*)$', views.outputDownload,
            {'document_root': STATICFILES_DIRS[1]}),
    re_path(r'tasks/(?P<taskUUID>.*)/results$',
            views.TaskResultsView),
    re_path(r'tasks/(?P<taskUUID>.*)/results/(?P<testTime>.*)/overview$',
            views.overviewGraph),
    re_path(r'^Reports/(?P<path>.*)$', views.outputDownload,
            {'document_root': OUTPUT_ROOT}),
    re_path(r'search', views.SearchView, name='search'),

    path('api', api_views.api_root),
    path('api/tasks', api_views.TaskInterface.as_view(), name='api-task'),
    path('api/tasks/<pk>', api_views.TaskView.as_view(), name='api-task-view'),
    path('api/nodes', api_views.NodeInterface.as_view(), name='api-node'),
    path('api/nodes/<pk>', api_views.NodeView.as_view(), name='api-node-view'),
    path('api/groups', api_views.GroupInterface.as_view(), name='api-group'),
    path('api/groups/<pk>', api_views.GroupView.as_view(), name='api-group-view')
]

nglogman/models.py
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.db.models import Q
import uuid

class LGNode(models.Model):
    """
    A data model that maps a Node entity to database
    """
    hostname = models.CharField(max_length=200)
    ip = models.GenericIPAddressField()
    port = models.IntegerField(default=50052)
    currentTask = models.UUIDField(null=True, editable=False)
    comments = models.TextField(default='')
    status = models.CharField(max_length=200,
                              editable=False, default='Offline')
    nodeUUID = models.UUIDField(primary_key=True, default=uuid.uuid4,
                                null=False, editable=True)

    def __str__(self):
        return str(self.ip) + ":" + str(self.port)

    class Meta:
        verbose_name = 'Logman Node'
        verbose_name_plural = 'Logman Nodes'


class NodeGroup(models.Model):
    """
    A data model that reflects a group of LGNode instances.
    """
    groupname = models.CharField(max_length=200)
    currentTask = models.UUIDField(null=True, editable=False)
    comments = models.TextField(default='', blank=True)
    nodes = models.ManyToManyField(LGNode)

    def __str__(self):
        return self.groupname


class Task(models.Model):
    """
    A data model that maps a Node entity to database
    """
    taskName = models.CharField(max_length=200, null=False)
    status = models.CharField(max_length=200,
                              editable=False, default='Scheduled')
    assignedNode = models.ForeignKey(NodeGroup, on_delete=models.CASCADE,
                                     verbose_name='Assigned Group')
    createTime = models.DateTimeField(auto_now=True)
    startTime = models.DateTimeField(null=False)
    duration = models.DurationField(null=False, help_text='{hh}:{mm}:{ss} or '
                                                          '{%s}')
    interval = models.PositiveSmallIntegerField(default=4, help_text='{%s}')
    taskUUID = models.UUIDField(primary_key=True, default=uuid.uuid4,
                                editable=False)

    def __str__(self):
        return self.taskName

    def clean(self):
        super().clean_fields()
        if self.startTime < timezone.now():
            raise ValidationError("Chosen start time has already passed.")

        qs = Task.objects.exclude(Q(status__exact='Completed') |
                                  Q(status__contains='Failed'))
        for task in qs:
            end = task.startTime + task.duration
            if task.startTime <= self.startTime <= end:
                busyNodes = []
                for node in self.assignedNode.nodes.all():
                    if node in task.assignedNode.nodes.all():
                        busyNodes.append(node.ip)
                raise ValidationError("The following nodes are unavailable"
                                      " at the specified time: \n %s"
                                      % ', '.join(busyNodes))

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Feather Icons -->
    <script src="https://unpkg.com/feather-icons"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/components.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />
    {% block csslinks %}
    {% endblock %}

    <title>NGLogman</title>
  </head>

  <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/dashboard">NGLogman Dashboard</a>
      <form role="form" action="/search" method="GET" style="width: 100%">
        <input class="form-control form-control-inline form-control-dark w-100" type="text" name="search_bar" placeholder="Search" aria-label="Search">
      </form>
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="/admin">Admin</a>
        </li>
      </ul>
  </nav>
  <body>
    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              {% block navitems %}
              {% endblock navitems %}
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">{% block titleheader %}{% endblock titleheader %}</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              {% block toggleButton %}
              {% endblock toggleButton %}
            </div>
          </div>
          {% if messages %}
            {% for message in messages %}
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR or message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
              <div class="alert alert-danger" role="alert">
              {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
              <div class="alert alert-primary" role="alert">
              {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
              <div class="alert alert-success" role="alert">
              {% endif %}
                  {{ message|safe }}
              </div>
            {% endfor %}
          {% endif %}

          {% block content_accordion %}
          {% endblock content_accordion %}
        </main>
      </div>
    </div>

    <script>feather.replace()</script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <script src="{% static 'js/are-you-sure.js' %}"></script>
    <script>
      $(function() {
          $('form').areYouSure();
      });
    </script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>

templates/config.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block titleheader %}
Configuration for '{{ group_name }}' <br>
{% endblock titleheader %}

{% block navitems %}
<li class="nav-item">
<a class="nav-link" href="/dashboard">
  <span data-feather="home"></span>
  Dashboard
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="/tasks">
  <span data-feather="clipboard"></span>
  Tasks
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="/groups">
  <span data-feather="package"></span>
  Groups
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="/nodes">
  <span data-feather="git-commit"></span>
  Nodes
</a>
</li>
{% endblock navitems %}

{% block content_accordion %}
<h4>Current Configs</h4>
<p>
    {% for node in all_nodes %}
    {% if node.status == 'Offline' %}
        <a href="/nodeConfigs/{{node.nodeUUID}}_config.ini" target="_blank">{{ node.ip }}:{{ node.port }}</a> (Offline)<br/>
    {% else %}
        <a href="/nodeConfigs/{{node.nodeUUID}}_config.ini" target="_blank">{{ node.ip }}:{{ node.port }}</a><br/>
    {% endif %}
    {% endfor %}
</p>
<h4>Upload New Config</h4>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
            {{field.label_tag}}
            {% if form.is_bound %}
                {% if field.errors %}
                    {% if field.name == 'file' %}
                        {% render_field field class="form-control-file is-invalid" %}
                    {% else %}
                        {% render_field field class="form-control is-invalid" %}
                    {% endif %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">
                          {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% if field.name == 'file' %}
                        {% render_field field class="form-control-file is-valid" %}
                    {% else %}
                        {% render_field field class="form-control is-valid" %}
                    {% endif %}
                {% endif %}
            {% else %}
                {% if field.name == 'file' %}
                    {% render_field field class="form-control-file" %}
                {% else %}
                    {% render_field field class="form-control" %}
                {% endif %}
            {% endif %}
            {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
        </div>
    {% endfor %}
    <input type="submit" value="Submit">
</form>
{% endblock content_accordion %}

templates/dashboard.html
{% extends 'base.html' %}

{% block titleheader %}
Dashboard
{% endblock titleheader %}

{% block navitems %}
<li class="nav-item">
<a class="nav-link active" href="dashboard">
  <span data-feather="home"></span>
  Dashboard <span class="sr-only">(current)</span>
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="tasks">
  <span data-feather="clipboard"></span>
  Task
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="groups">
  <span data-feather="package"></span>
  Groups
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="nodes">
  <span data-feather="git-commit"></span>
  Nodes
</a>
</li>
{% endblock navitems %}

{% block content_accordion %}
    <h3>Node Groups:
        <a href="groups"><font size="2">Details</font></a> </h3>
{% if node_groups %}
{% for group in node_groups %}
    <div class="card">
        <div class="card-header" id="heading-grp-{{forloop.counter}}">
            {{ group.groupname}} ({{ group.node_count }} nodes)
        </div>
    </div>
    {% endfor %}
{% else %}
    <div class="alert alert-danger" role="alert">
        There are no node groups.
    </div>
{% endif %}
<br/>
    <h3>Available Nodes:
        <a href="nodes"><font size="2">Details</font></a> </h3>
{% if available_node_set %}
{% for node in available_node_set %}
    <div class="card border-success mt-2">
        <div class="card-header" id="heading-{{forloop.counter}}">
            {{node.hostname}} @ {{node.ip}}:{{node.port}}
        </div>
    </div>
    {% endfor %}
{% else %}
    <div class="alert alert-danger" role="alert">
        There are no available nodes.
    </div>
{% endif %}
{% if task_set %}
<br/>
    <h3>Scheduled Tasks:
    <a href="tasks"><font size="2">Details</font></a> </h3>
    {% for task in task_set %}
    <div class="card mt-2">
        <div class="card-header" id="heading-task-{{forloop.counter}}">
            <h2 class="mb-0">
                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse-task-{{forloop.counter}}" aria-expanded="true" aria-controls="collapse-task-{{forloop.counter}}">
                    {{task.taskName}}
                </button>
            </h2>
        </div>
        <div id="collapse-task-{{forloop.counter}}" class="collapse" aria-labelledby="heading-task-{{forloop.counter}}" data-parent="#taskAccordion">
            <div class="card-body">
                Creation Time: {{task.createTime}} <br/>
                Start Time: {{task.startTime}} <br/>
                Task UUID: {{task.taskUUID}} <br/>
            </div>
        </div>
    </div>
    {% endfor %}
{% elif not in_progress %}
    <br/>
    <h3>Scheduled Tasks:
    <a href="tasks"><font size="2">Details</font></a> </h3>
    <div class="alert alert-danger" role="alert">
        There are no upcoming tasks.
    </div>
    {% endif %}
{% if in_progress %}
<br/>
    <h3>In Progress Tasks:
    <a href="tasks"><font size="2">Details</font></a> </h3>
    {% for task in in_progress %}
    <div class="card border-warning mt-2">
        <div class="card-header" id="heading-progress-{{forloop.counter}}">
            <h2 class="mb-0">
                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse-progress-{{forloop.counter}}" aria-expanded="true" aria-controls="collapse-progress-{{forloop.counter}}">
                    {{task.taskName}}
                </button>
            </h2>
        </div>
        <div id="collapse-progress-{{forloop.counter}}" class="collapse" aria-labelledby="heading-progress-{{forloop.counter}}">
            <div class="card-body">
                Creation Time: {{task.createTime}} <br/>
                Start Time: {{task.startTime}} <br/>
                Task UUID: {{task.taskUUID}} <br/>
            </div>
        </div>
    </div>
    {% endfor %}
{% endif %}
{% endblock content_accordion %}

templates/groups.html
{% extends 'base.html' %}

{% block titleheader %}
List of Groups
{% endblock titleheader %}

{% block navitems %}
<li class="nav-item">
<a class="nav-link" href="dashboard">
  <span data-feather="home"></span>
  Dashboard
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="tasks">
  <span data-feather="clipboard"></span>
  Tasks
</a>
</li>
<li class="nav-item">
<a class="nav-link active" href="groups">
  <span data-feather="package"></span>
  Groups <span class="sr-only">(current)</span>
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="nodes">
  <span data-feather="git-commit"></span>
  Nodes
</a>
</li>
{% endblock navitems %}

{% block toggleButton %}
<form action="#" method="get">
 <input type="submit" class="btn btn-primary" value="Refresh" name="refresh">
</form>
{% endblock toggleButton %}

{% block content_accordion %}
{% if node_groups %}
{% for grp in node_groups %}
    <div class="card mt-2">
        <div class="card-header" id="heading-{{forloop.counter}}">
            <h2 class="mb-0">
                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse-{{forloop.counter}}" aria-expanded="true" aria-controls="collapse-{{forloop.counter}}">
                    {{grp.groupname}} ({{grp.node_count}} nodes)
                </button>
            </h2>
        </div>
        <div id="collapse-{{forloop.counter}}" class="collapse" aria-labelledby="heading-{{forloop.counter}}">
            <div class="card-body">
                Nodes: <br/>
                <p style="margin-left:30px">
                {% for node in grp.nodes.all %}
                    {% if node.status == 'Available' %}
                        <status-indicator positive pulse></status-indicator>
                    {% elif node.status == 'Busy' %}
                        <status-indicator intermediary pulse></status-indicator>
                    {% else %}
                        <status-indicator negative pulse></status-indicator>
                    {% endif %}
                    {{node.hostname}} @ {{node.ip}}:{{node.port}}
                    <br/>
                {% endfor %}
                </p>
                Current Task: {{grp.currentTask}}<br/>
                {% if grp.comments %}
                    Comments: {{grp.comments}}<br/>
                {% endif %}
                <br/>
                <a href="groups/{{grp.id}}/config">Configure...</a>
            </div>
        </div>
    </div>
{% endfor %}
{% else %}
    <div class="alert alert-danger" role="alert">
        There are no groups to display.
    </div>
{% endif %}
{% endblock content_accordion %}

templates/nodes.html
{% extends 'base.html' %}

{% block titleheader %}
List of Available Nodes
{% endblock titleheader %}

{% block navitems %}
<li class="nav-item">
<a class="nav-link" href="dashboard">
  <span data-feather="home"></span>
  Dashboard
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="tasks">
  <span data-feather="clipboard"></span>
  Tasks
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="groups">
  <span data-feather="package"></span>
  Groups
</a>
</li>
<li class="nav-item">
<a class="nav-link active" href="nodes">
  <span data-feather="git-commit"></span>
  Nodes <span class="sr-only">(current)</span>
</a>
</li>
{% endblock navitems %}

{% block toggleButton %}
<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseOffline" aria-expanded="false" aria-controls="collapseOffline">Toggle Offline</button>
<form action="#" method="get">
 <input type="submit" class="btn btn-primary" value="Refresh" name="refresh">
</form>
{% endblock toggleButton %}

{% block content_accordion %}
{% if offline_node_set or available_node_set %}
{% for node in available_node_set %}
    {% if node.status == 'Busy' %}
    <div class="card border-warning">
    {% else %}
    <div class="card border-success">
    {% endif %}
        <div class="card-header" id="heading-{{forloop.counter}}">
            <h2 class="mb-0">
                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse-{{forloop.counter}}" aria-expanded="true" aria-controls="collapse-{{forloop.counter}}">
                    {{node.hostname}}
                </button>
            </h2>
        </div>
        <div id="collapse-{{forloop.counter}}" class="collapse" aria-labelledby="heading-{{forloop.counter}}">
            <div class="card-body">
                Status: {{node.status}}<br/>
                {% if node.status == 'Busy' %}
                Task ID: {{node.currentTask}}<br/>
                {% endif %}
                IP Address: {{node.ip}}<br/>
                Access Port: {{node.port}}<br/>
                UUID: {{node.nodeUUID}}<br/>
                {% if node.comments != '' %}
                Comments: node.comments
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <div class="collapse" id="collapseOffline">
        {% for node in offline_node_set %}
        <div class="card border-danger">
            <div class="card-header" id="heading-offline-{{forloop.counter}}">
                <h2 class="mb-0">
                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse-offline-{{forloop.counter}}" aria-expanded="false" aria-controls="collapse-offline-{{forloop.counter}}">
                        {{node.hostname}}
                    </button>
                </h2>
            </div>
            <div id="collapse-offline-{{forloop.counter}}" class="collapse" aria-labelledby="heading-offline-{{forloop.counter}}">
                <div class="card-body">
                    Status: {{node.status}}<br/>
                    IP Address: {{node.ip}}<br/>
                    Access Port: {{node.port}}<br/>
                    UUID: {{node.nodeUUID}}<br/>
                    {% if node.comments != '' %}
                    Comments: node.comments
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% else %}
    <div class="alert alert-danger" role="alert">
        There are no nodes to display.
    </div>
{% endif %}
</div>
{% endblock content_accordion %}

templates/overview.html
{% extends 'base.html' %}

{% block csslinks %}
<link href="http://cdn.pydata.org/bokeh/release/bokeh-1.0.4.min.css" rel="stylesheet" type="text/css">
<link href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-1.0.4.min.css" rel="stylesheet" type="text/css">
{% endblock %}

{% block titleheader %}
Task Overview
{% endblock titleheader %}

{% block navitems %}
<li class="nav-item">
<a class="nav-link" href="/dashboard">
  <span data-feather="home"></span>
  Dashboard
</a>
</li>
<li class="nav-item">
<a class="nav-link active" href="/tasks">
  <span data-feather="clipboard"></span>
  Tasks  <span class="sr-only">(current)</span>
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="/groups">
  <span data-feather="package"></span>
  Groups
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="/nodes">
  <span data-feather="git-commit"></span>
  Nodes
</a>
</li>
{% endblock navitems %}

{% block content_accordion %}
    {{ bokehDiv | safe }}
{% endblock content_accordion %}

{% block scripts %}
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-1.0.4.min.js"></script>
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-widgets-1.0.4.min.js"></script>
    {{ bokehScript | safe }}
{% endblock %}

templates/results.html
{% extends 'base.html' %}
{% load ngutils %}

{% block titleheader %}
Results for {{ task.taskName }}
{% endblock titleheader %}

{% block navitems %}
<li class="nav-item">
<a class="nav-link" href="/dashboard">
  <span data-feather="home"></span>
  Dashboard
</a>
</li>
<li class="nav-item">
<a class="nav-link active" href="/tasks">
  <span data-feather="clipboard"></span>
  Tasks  <span class="sr-only">(current)</span>
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="/groups">
  <span data-feather="package"></span>
  Groups
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="/nodes">
  <span data-feather="git-commit"></span>
  Nodes
</a>
</li>
{% endblock navitems %}

{% block content_accordion %}
{% for test in test_list %}
    <div class="card w-75">
      <div class="card-body">
        <h5 class="card-title">{{ test|timeformat }}</h5>
        <a href="results/{{ test }}/overview" class="btn btn-primary btn-sm">View Graph</a>
        <a href="/Reports/{{task.taskName}}_{{task.taskUUID}}/{{ test }}/overview.xlsx" target="_blank" class="btn btn-primary btn-sm">Download Summary</a>
        <form action="#" method="post" style="display:inline">
          {% csrf_token %}
          <button name="delete" class="btn btn-danger btn-sm" value="{{ test }}" onclick="return confirm('Are you sure you want to delete this item?');">Delete</button>
        </form>
      </div>
    </div>
{% endfor %}
{% endblock content_accordion %}